# Generated by Django 3.1 on 2020-09-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venderName', models.CharField(max_length=100)),
                ('venderNumber', models.IntegerField()),
                ('senderName', models.CharField(max_length=100)),
                ('senderEmail', models.EmailField(max_length=254)),
                ('senderCountryOfOrigin', models.CharField(max_length=100)),
                ('walmartbuyerName', models.CharField(max_length=100)),
                ('upcEAN', models.IntegerField()),
                ('itemType', models.CharField(max_length=100)),
                ('departmentNumber', models.IntegerField()),
                ('inlaySpec', models.CharField(max_length=100)),
                ('inalyDeveloper', models.CharField(max_length=100)),
                ('modelName', models.CharField(max_length=100)),
            ],
        ),
    ]
