# Generated by Django 3.1 on 2020-10-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Entry',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('vendorName', models.CharField(max_length=100)),
                ('vendorNumber', models.IntegerField()),
                ('senderName', models.CharField(max_length=100)),
                ('senderEmail', models.EmailField(max_length=254)),
                ('senderCountryOfOrigin', models.CharField(max_length=100)),
                ('walmartBuyerName', models.CharField(max_length=100)),
                ('upcEAN', models.IntegerField()),
                ('itemType', models.CharField(max_length=100)),
                ('departmentNumber', models.IntegerField()),
                ('inlaySpec', models.CharField(max_length=100)),
                ('inlayDeveloper', models.CharField(max_length=100)),
                ('modelName', models.CharField(max_length=100)),
            ],
        ),
    ]
