# Generated by Django 3.1 on 2020-09-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walmart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_entry',
            old_name='inalyDeveloper',
            new_name='inlayDeveloper',
        ),
    ]
