# Generated by Django 3.1 on 2020-09-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walmart', '0002_auto_20200924_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_entry',
            name='ID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
