# Generated by Django 3.1 on 2020-09-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walmart', '0003_form_entry_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_entry',
            name='id',
        ),
        migrations.AlterField(
            model_name='form_entry',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
