# Generated by Django 3.1 on 2020-09-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walmart', '0004_auto_20200924_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_entry',
            old_name='walmartbuyerName',
            new_name='walmartBuyerName',
        ),
    ]
