# Generated by Django 3.1 on 2020-10-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walmart', '0005_auto_20200928_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_entry',
            old_name='venderName',
            new_name='vendorName',
        ),
        migrations.RenameField(
            model_name='form_entry',
            old_name='venderNumber',
            new_name='vendorNumber',
        ),
    ]
